# Generated by Django 5.0.6 on 2026-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=50, unique=True)),
                ('cargo_type', models.CharField(choices=[('medicine', 'Medicine'), ('food', 'Food Supplies'), ('agricultural_produce', 'Agricultural Produce'), ('construction_material', 'Construction Material'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delayed', 'Delayed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_departure', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
