# Generated by Django 5.0.6 on 2026-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200)),
                ('destination_name', models.CharField(max_length=200)),
                ('source_latitude', models.FloatField()),
                ('source_longitude', models.FloatField()),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('fastest_time_minutes', models.FloatField(blank=True, null=True)),
                ('safest_time_minutes', models.FloatField(blank=True, null=True)),
                ('delay_minutes', models.FloatField(blank=True, null=True)),
                ('recommended', models.CharField(default='safest', help_text='fastest | safest', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
