# Generated by Django 5.0.6 on 2026-09-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('road_type', models.CharField(choices=[('highway', 'Highway'), ('state_road', 'State Road'), ('rural_road', 'Rural Road'), ('bridge', 'Bridge')], default='state_road', max_length=20)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('length_km', models.FloatField(help_text='Segment length in kilometres')),
                ('base_travel_time_minutes', models.FloatField(help_text='Travel time under normal conditions')),
                ('status', models.CharField(choices=[('open', 'Open'), ('risky', 'Risky'), ('blocked', 'Blocked'), ('under_repair', 'Under Repair')], default='open', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('risk_probability', models.FloatField(default=0.0, help_text='0-1 ML-predicted disruption probability')),
                ('landslide_prone', models.BooleanField(default=False)),
                ('flood_prone', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='roads.district')),
            ],
            options={
                'indexes': [models.Index(fields=['district', 'status'], name='roads_road_distric_2a0238_idx')],
            },
        ),
    ]
