# Generated by Django 5.0.6 on 2026-09-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_mm_24h', models.FloatField(default=0)),
                ('rainfall_mm_72h', models.FloatField(default=0)),
                ('temperature_celsius', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, help_text='e.g. Heavy Rain, Clear, Fog', max_length=100)),
                ('forecast_next_24h', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='manual', help_text='manual | api_sync | simulator', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='roads.district')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
