# Generated by Django 5.0.6 on 2026-09-17 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('cargo_type', models.CharField(help_text='e.g. Medicine, Food, Construction Material', max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_kmph', models.FloatField(default=0)),
                ('heading_degrees', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('moving', 'Moving'), ('stopped', 'Stopped'), ('delayed', 'Delayed'), ('delivered', 'Delivered'), ('breakdown', 'Breakdown')], default='moving', max_length=20)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_kmph', models.FloatField(default=0)),
                ('recorded_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
