# Generated by Django 5.0.6 on 2026-09-17 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('incident_type', models.CharField(choices=[('landslide', 'Landslide'), ('flood', 'Flood'), ('heavy_rainfall', 'Heavy Rainfall'), ('road_damage', 'Road Damage'), ('bridge_damage', 'Bridge Damage'), ('traffic_congestion', 'Traffic Congestion'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incidents/%Y/%m/')),
                ('district_name', models.CharField(blank=True, max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(help_text='When the incident happened on the ground')),
                ('synced_at', models.DateTimeField(auto_now_add=True, help_text='When the server received it')),
                ('created_offline', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
